"""Versioned SCAR IR v2 building blocks.

This package is intentionally isolated from the v1 graph and planner.  It
defines identities, semantic definitions, execution evidence and value
provenance; it does not select or apply an optimization backend.
"""

from .ids import (
    ContractID,
    ControlRegionID,
    CorrespondenceID,
    EffectSummaryID,
    MaterializationID,
    MeasurementID,
    ModuleID,
    ObjectID,
    OperationDefinitionID,
    OperationInstanceID,
    OptimizationRegionID,
    PackageID,
    PlanAlternativeID,
    PlanID,
    ProvenanceID,
    LogicalValueID,
    ResourceID,
    SourceAtomID,
    StorageAllocationID,
    StorageRegionID,
    ValueSlotID,
    ValueVersionID,
)
from .common import (
    Completeness,
    EvidenceClaim,
    EvidenceKind,
    ProofClaim,
    ProofStatus,
    SourceReference,
)
from .contracts import (
    ContractDefinition,
    ContractFacet,
    EffectPresence,
    EffectSet,
    EffectSummary,
    EffectTarget,
    EffectTargetKind,
    FacetRequirement,
    MeasurementRecord,
    ResourceKind,
    ResourceRequirement,
)
from .values import (
    BindingRelation,
    EquivalenceClaim,
    LogicalValue,
    Materialization,
    ObjectBinding,
    ProvenanceRecord,
    ProvenanceRelation,
    StorageAllocation,
    StorageRegion,
    ValueGraph,
    ValueVersion,
)
from .semantic import (
    ControlRegion,
    ModuleDefinition,
    OperationDefinition,
    OperationKind,
    PackageDefinition,
    SemanticEdge,
    SemanticEndpoint,
    SemanticGraph,
    SemanticNodeKind,
    SemanticRelation,
    SourceAtom,
    ValueSlot,
)
from .evidence import (
    EvidenceEdge,
    EvidenceEndpoint,
    EvidenceGraph,
    EvidenceNodeKind,
    EvidenceRelation,
    EvidenceStatus,
    OperationInstance,
    ValueObservation,
)
from .correspondence import (
    CorrespondenceGraph,
    CorrespondenceKind,
    CorrespondenceRecord,
)
from .optimization import (
    CostRequest,
    GuardSpec,
    InstructionKind,
    InvalidationSpec,
    LiteralValue,
    MeasurementMode,
    OptimizationContext,
    OptimizationGraph,
    OptimizationRegion,
    PlanAlternative,
    PlanDisposition,
    PlanInstruction,
    PlanSelection,
    RegionGranularity,
    RegionMove,
    RegionPort,
    RegionPortKind,
    ResidualEffect,
    TransformDelta,
    TransformKind,
    ValidationRequest,
    ValuePattern,
    ValueSubstitution,
)
from .schemas import IRBundle, canonical_json, optimization_context
from .codec import bundle_from_dict, bundle_from_json

__all__ = [
    "ContractID", "ControlRegionID", "CorrespondenceID", "EffectSummaryID",
    "MaterializationID", "MeasurementID", "ModuleID", "ObjectID",
    "OperationDefinitionID", "OperationInstanceID", "OptimizationRegionID",
    "PackageID", "PlanAlternativeID", "PlanID", "ProvenanceID",
    "LogicalValueID", "ResourceID", "SourceAtomID", "StorageAllocationID",
    "StorageRegionID", "ValueSlotID", "ValueVersionID", "BindingRelation",
    "EquivalenceClaim", "LogicalValue", "Materialization", "ObjectBinding",
    "ProvenanceRecord", "ProvenanceRelation", "StorageAllocation",
    "StorageRegion", "ValueGraph", "ValueVersion", "Completeness",
    "EvidenceClaim", "EvidenceKind", "ProofClaim", "ProofStatus",
    "SourceReference", "ContractDefinition", "ContractFacet", "EffectPresence",
    "EffectSet", "EffectSummary", "EffectTarget", "EffectTargetKind",
    "FacetRequirement", "MeasurementRecord", "ResourceKind",
    "ResourceRequirement", "ControlRegion", "ModuleDefinition",
    "OperationDefinition", "OperationKind", "PackageDefinition", "SemanticEdge",
    "SemanticEndpoint", "SemanticGraph", "SemanticNodeKind", "SemanticRelation",
    "SourceAtom", "ValueSlot", "EvidenceEdge", "EvidenceEndpoint",
    "EvidenceGraph", "EvidenceNodeKind", "EvidenceRelation", "EvidenceStatus",
    "OperationInstance", "ValueObservation", "CostRequest", "GuardSpec",
    "CorrespondenceGraph", "CorrespondenceKind", "CorrespondenceRecord",
    "InstructionKind", "InvalidationSpec", "LiteralValue", "MeasurementMode",
    "OptimizationContext", "OptimizationGraph", "OptimizationRegion",
    "PlanAlternative", "PlanDisposition", "PlanInstruction", "PlanSelection",
    "RegionGranularity", "RegionMove", "RegionPort", "RegionPortKind",
    "ResidualEffect", "TransformDelta", "TransformKind", "ValidationRequest",
    "ValuePattern", "ValueSubstitution", "IRBundle", "canonical_json",
    "optimization_context",
    "bundle_from_dict", "bundle_from_json",
]
